const sqlite3 = require('sqlite3').verbose();
const db = new sqlite3.Database('./english_hero.db');

const wordsRaw = `
a art. 一(個)
A.M. adv. 上午
ability noun 能力、才能
able adj. 能夠的、有才能的
about prep./adv. 大約、關於；大約、幾乎、在周圍
above prep./adv. 在…上面、超過、大於
abroad adv. 在國外、到國外
absent adj. 缺席的、不在場的、心不在焉的
accept verb 收受、接受(提議、邀請)、同意、接納
accident noun 意外事故
achieve verb 達到、完成、實現
across prep./adv. 橫過、在對面
act noun/verb 表演者、演出、扮演
action noun 行動、行為、動作
active adj. 活躍的、積極的
activity noun 活動
actor noun 演員
actress noun 女演員
actually adv. 實際上、事實上
add verb 加上、增加、補充說
addition noun 加法、添加
address noun 地址、網址、位址；演講、演說
admire verb 欽佩、欣賞
admit verb 承認；准許進入
adopt verb 領養、接受、採納
adult noun/adj. 成年人；成年的
advance verb (使)前進、使發展、促進
advantage noun 優點、優勢、好處
adventure noun 冒險、奇遇
advertisement noun 廣告
advice noun 建議、忠告
advise verb 建議、忠告
affair noun 事務、事件
affect verb 影響、(疾病)感染
afraid adj. 害怕的、擔憂的
afternoon noun 下午
again adv. 又、再一次
against prep. 反對、與...相反
age noun 年齡、老化
ago adv. 在…以前
agree verb 同意、贊成、相符
ahead adv. 在前面、領先、提早
aid noun/verb 幫助、援助
aim verb/noun 計劃、目標、瞄準
air noun 空氣、空中
air conditioner noun 冷氣機、空調
aircraft noun 飛機
airline noun 航空公司
airplane noun 飛機
airport noun 機場
alarm noun 鬧鐘、警報
album noun 相簿、音樂專輯
alike adv./adj. 相似地、同樣地
alive adj. 活著的、仍然存在的
allow verb 准許
almost adv. 幾乎、差不多
alone adv./adj. 單獨(的)、獨自(的)
along prep. 沿著
aloud adv. 大聲地
alphabet noun 字母表
already adv. 已經
also adv. 也、此外
although conj. 雖然
altogether adv. 全部、總共
always adv. 總是、一直
ambulance noun 救護車
America noun 美國、美洲
American adj./noun 美國的、美國人
among prep. 在...之中
amount noun 數量
ancient adj. 古代的、古老的
angel noun 天使
anger noun 憤怒、怒氣
angry adj. 生氣的、憤怒的
animal noun 動物
ankle noun 腳踝
another pron./adj. 另一個、另外的
answer noun/verb 答案、回答
ant noun 螞蟻
anybody pron. 任何人
anymore adv. 再也不、不再
anyone pron. 任何人
anything pron. 任何東西、任何事情
anytime adv. 在任何時候
anyway adv. 無論如何、反正
anywhere adv. 任何地方
apartment noun 公寓
apologize verb 道歉
appear verb 出現、顯現
appearance noun 出現、外貌
apple noun 蘋果
apply verb 申請、請求；應用
appreciate verb 欣賞、感激
April noun 四月
area noun 地區、範圍、面積
argue verb 爭吵、爭論
arm noun 手臂、袖子
armchair noun 扶手椅
army noun 軍隊、陸軍
around prep./adv. 圍繞、在...附近
arrange verb 安排、籌劃
arrest verb/noun 逮捕
arrive verb 到達、來臨
art noun 藝術、美術
article noun 文章、報導；物品
artist noun 藝術家、畫家
Asia noun 亞洲
Asian adj./noun 亞洲的、亞洲人
ask verb 詢問、請求
asleep adj. 睡著的
assistant noun/adj. 助手、助理
assume verb 假設
attack noun/verb 攻擊、進攻
attend verb 出席、參加
attention noun 注意力、關注
audience noun 聽眾、觀眾
August noun 八月
aunt noun 姑姑、阿姨
Australia noun 澳洲
autumn noun 秋天
available adj. 有空的、可獲得的
avoid verb 避免、避開
aware adj. 意識到、發覺
away adv. 去別處、逐漸消失
baby noun 嬰兒、寶貝
back noun/adj. 背部、後面
bad adj. 壞的、不好的
badly adv. 差地、嚴重地
badminton noun 羽毛球
bag noun 袋子
bake verb 烘烤
bakery noun 麵包店
balcony noun 陽台
ball noun 球
balloon noun 氣球
banana noun 香蕉
band noun 樂團、樂隊
bank noun 銀行；堤、岸
banker noun 銀行家
bar noun 條狀物、酒吧
barbecue noun/verb 烤肉、燒烤
barber noun 理髮師
bark verb/noun 吠叫、狗吠聲
base verb/noun 基地、基礎
baseball noun 棒球
basement noun 地下室
basic adj. 基本的
basis noun 基礎、根據
basket noun 籃子
basketball noun 籃球
bat noun 蝙蝠；球棒
bath noun/verb 沐浴、洗澡
bathroom noun 浴室、廁所
beach noun 海灘、湖濱
bean noun 豆子
bear noun 熊
beard noun 鬍鬚
beat verb 打敗、戰勝
beautiful adj. 美麗的
because conj. 因為
become verb 成為、變得
bed noun 床、床位
bedroom noun 臥室
bee noun 蜜蜂
beef noun 牛肉
beer noun 啤酒
begin verb 開始
beginner noun 初學者
beginning noun 開端
behave verb 表現
behind prep./adv. 在…後面
belief noun 相信、信念
believe verb 相信
bell noun 鈴、鐘
belong verb 屬於
below adv./prep. 在...下面
belt noun 腰帶
bench noun 長椅
beside prep. 在...旁邊
besides prep./adv. 除…之外
best adv./adj. 最好的
better adv./adj. 更好的
between prep. 在…之間
beyond prep./adv. 遠於、超出
bicycle noun 腳踏車
big adj. 大的、重大的
bill noun/verb 鈔票、帳單
biology noun 生物學
bird noun 鳥
birthday noun 生日
bit noun 稍微、一點點
bite verb/noun 咬、叮
bitter adj. 有苦味的
black adj./noun 黑色的；黑色
blackboard noun 黑板
blame verb/noun 責備
blank adj./noun 空白的；空格
blanket noun/verb 毛毯、毯子
blind adj./verb 失明的、盲目的
block noun 街區；大樓
blood noun 血液、血統
blouse noun 女襯衫
blow verb 吹
blue adj./noun 藍色的；藍色
board verb/noun 上(交通工具)
boat noun 船
body noun 身體、屍體
boil verb 沸騰
bomb noun/verb 炸彈；轟炸
bone noun 骨頭
book noun 書
bookcase noun 書架
bookstore noun 書店
bored adj. 感到無聊的
boring adj. 無聊的
born verb/adj. 出生、天生的
borrow verb 借入
boss noun 老闆
both adv./adj./pron. 兩個、雙方
bother verb/noun 打擾、麻煩
bottle noun/verb 瓶子
bottom noun/adj./verb 底部、屁股
bow verb/noun 鞠躬、點頭
bowl noun 碗、缽
bowling noun 保齡球運動
box noun/verb 箱、盒
boy noun 男孩
brain noun 頭腦
branch noun 樹枝、分支
brave adj. 勇敢的
bread noun 麵包
break verb/noun 打破、休息
breakfast noun 早餐
brick noun 磚塊
bridge noun/verb 橋
brief adj. 簡短的
bright adj. 明亮的、聰明的
bring verb 帶來
Britain noun 英國
broad adj. 寬廣的
broadcast noun/verb 廣播
brother noun 兄弟
brown adj./noun/verb 棕色的
brunch noun 早午餐
brush noun/verb 刷子、刷抹
bucket noun 水桶
buffet noun 自助餐
bug noun 小蟲子、漏洞
build verb 建造
building noun 建築物
bun noun 小圓麵包
bundle noun 束、捆
burn verb 燃燒、著火
burst verb/noun 爆炸
bus noun 公車
business noun 生意、公司
businessperson noun 商人
busy adj. 忙碌的
but adv./conj./prep. 但是
butter noun/verb 奶油
butterfly noun 蝴蝶
button noun/verb 鈕扣
buy verb/noun 買
by prep./adv. 藉由、經過
cabbage noun 包心菜
cabinet noun 櫥櫃
cable noun/verb 電纜、有線電視
cafe noun 咖啡館
cafeteria noun 自助餐廳
cage noun/verb 籠子
cake noun 蛋糕
calendar noun 日曆
call verb/noun 打電話、呼叫
calm adj./verb/noun 冷靜的
camera noun 照相機
camp noun/verb 露營、營地
campus noun 校園
can aux. 能、可以
Canada noun 加拿大
cancel verb 取消
cancer noun 癌症
candle noun 蠟燭
candy noun 糖果
cap noun/verb 便帽
captain noun 隊長
car noun 汽車
card noun 卡片
care noun/verb 照顧、擔憂
career noun 職業
careful adj. 小心的
careless adj. 粗心的
carpet noun/verb 地毯
carrot noun 胡蘿蔔
carry verb 搬運
cartoon noun 卡通
case noun 箱、案例
cash noun/verb 現金
castle noun 城堡
cat noun 貓
catch verb/noun 捕捉、趕上
cause verb/noun 導致
CD noun 光碟
ceiling noun 天板
celebrate verb 慶祝
cell noun 細胞、手機
cellphone noun 手機
cent noun 分
center noun/verb 中心
centimeter noun 公分
central adj. 中心的
century noun 一百年
cereal noun 穀物
certain adj. 肯定的
certainly adv. 必定
chair noun 椅子
chairperson noun 主席
chalk noun/verb 粉筆
chance noun 機會
change verb/noun 改變、零錢
channel noun 頻道
chapter noun 章節
character noun 角色、個性
charge verb/noun 收費、指控
chart noun 圖表
chase verb 追趕
chat verb/noun 聊天
cheap adj./adv. 便宜的
cheat verb/noun 欺騙
check noun/verb 檢查、支票
cheer verb/noun 歡呼
cheese noun 起司
chemical noun/adj. 化學的
chess noun 西洋棋
chicken noun 雞肉
chief adj./noun 首要的
child noun 小孩
childhood noun 童年
childish adj. 孩子氣的
childlike adj. 孩子般的
chin noun 下巴
China noun 中國
Chinese noun/adj. 中文、中國人
chocolate noun 巧克力
choice noun/adj. 選擇
choose verb 選擇
chopstick noun 筷子
Christmas noun 聖誕節
chubby adj. 圓胖的
church noun 教堂
circle noun/verb 圓圈
citizen noun 公民
city noun 城市
claim verb/noun 聲稱、權利
clap verb/noun 拍手
class noun 課、等級
classic adj./noun 古典的
classroom noun 教室
clean adj./verb/noun 乾淨的
clear verb/adj./adv. 清楚的
clerk noun 店員
clever adj. 聰明的
click verb/noun 點按
climate noun 氣候
climb verb/noun 爬
clock noun 時鐘
close verb/adj./adv. 關閉、靠近
closet noun 衣櫥
clothes noun 衣服
cloudy adj. 多雲的
club noun 俱樂部
coach noun/verb 教練
coast noun 海岸
coat noun 外套
cockroach noun 蟑螂
coffee noun 咖啡
coin noun 硬幣
Coke noun 可口可樂
cola noun 可樂
cold adj./noun 冷的、感冒
collect verb 收集
collection noun 收藏品
college noun 大學
color noun/verb 顏色
colorful adj. 色彩豐富的
comb noun/verb 梳子
come verb 來
comfortable adj. 舒適的
comic adj./noun 漫畫、滑稽的
command verb/noun 命令
comment noun/verb 評論
common adj. 常見的
company noun 公司
compare verb 比較
complain verb 抱怨
complete verb/adj. 完成、完整的
computer noun 電腦
concern noun/verb 擔心
confident adj. 自信的
confirm verb 確認
conflict noun 衝突
Confucius noun 孔子
confuse verb 使困惑
congratulation noun 祝賀
consider verb 考慮
contact noun/verb 聯繫
contact lens noun 隱形眼鏡
contain verb 包含
continue verb 繼續
contract noun/verb 合約
control noun/verb 控制
convenience store noun 便利商店
convenient adj. 方便的
conversation noun 對話
cook verb/noun 烹調、廚師
cookie noun 餅乾
cool adj./verb 涼快的、酷的
copy noun/verb 副本、複製
corn noun 玉米
corner noun 角落
correct adj./verb 正確的
cost noun/verb 費用
cotton noun 棉
couch noun 沙發
cough verb/noun 咳嗽
could aux. 能
count verb/noun 數、計算
country noun 國家
countryside noun 鄉間
county noun 縣
couple noun 一對
courage noun 勇氣
course noun 課程
court noun 法庭
cousin noun 堂兄弟姊妹
cover verb/noun 遮蓋
cow noun 母牛
crab noun 螃蟹
crayon noun 蠟筆
crazy adj. 瘋狂的
cream noun 乳霜
create verb 創造
credit card noun 信用卡
crime noun 罪行
crisis noun 危機
cross verb/noun 穿越、十字架
crowd noun 人群
crowded adj. 擁擠的
cruel adj. 殘酷的
cry verb/noun 哭泣
culture noun 文化
cup noun 杯子
cure noun/verb 治癒
curious adj. 好奇的
current adj./noun 當前的、水流
curtain noun 窗簾
curve noun/verb 曲線
custom noun 習俗
customer noun 顧客
cut verb/noun 切、割
cute adj. 可愛的
dad noun 爸爸
daily adj./adv. 每日的
damage noun/verb 損害
dance verb/noun 跳舞
danger noun 危險
dangerous adj. 危險的
dark noun/adj. 黑暗
data noun 資料
date noun/verb 日期、約會
daughter noun 女兒
dawn noun/verb 黎明
day noun 天
dead adj. 死亡的
deaf adj. 聾的
deal verb/noun 交易、處理
dear adj./noun 親愛的
death noun 死亡
debate noun/verb 辯論
debt noun 債務
December noun 十二月
decide verb 決定
decision noun 決定
decorate verb 裝飾
decrease verb/noun 減少
deep adj./adv. 深的
deer noun 鹿
degree noun 程度
delay noun/verb 延誤
delicious adj. 美味的
deliver verb 運送
democracy noun 民主
democratic adj. 民主的
dentist noun 牙醫
deny verb 否認
department noun 部門
department store noun 百貨公司
depend verb 取決於
describe verb 描述
desert verb/noun 遺棄、沙漠
design noun/verb 設計
desire noun/verb 渴望
desk noun 書桌
dessert noun 甜點
determine verb 決定
develop verb 發展
dial verb/noun 撥號
diamond noun 鑽石
diary noun 日記
dictionary noun 字典
die verb 死
diet noun/verb 飲食
difference noun 差別
different adj. 不同的
difficult adj. 困難的
difficulty noun 困難
dig verb 挖
diligent adj. 勤奮的
`;

async function main() {
    const lines = wordsRaw.trim().split('\n');
    let count = 0;
    
    db.serialize(() => {
        const stmt = db.prepare("INSERT OR IGNORE INTO words (english, chinese, category) VALUES (?, ?, ?)");
        
        for (const line of lines) {
            const parts = line.trim().split(/\s+/);
            if (parts.length >= 3) {
                const english = parts[0];
                const chinese = parts.slice(2).join(' ');
                stmt.run(english, chinese, '初級');
                count++;
            }
        }
        
        stmt.finalize(() => {
            console.log(`Successfully imported ${count} words from PDF extraction.`);
            db.close();
        });
    });
}

main().catch(err => console.error(err));
